# Generated by Django 5.2.10 on 2026-02-02 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave_request', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaverequest',
            old_name='first_name',
            new_name='user_firstname',
        ),
        migrations.RenameField(
            model_name='leaverequest',
            old_name='last_name',
            new_name='user_lastname',
        ),
    ]
